settings:
  digits: 3
  itemformat: yaml
  prefix: REQ
  sep: '-'
attributes:
  publish:
    - rationale
  defaults:
    title: "Software Patterns through Dungeon Crawler/Text Adventure"
extensions:
  item_sha_required: true
